# Generated by Django 3.2.25 on 2024-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='slug', unique=True, verbose_name='Уникальный id'),
            preserve_default=False,
        ),
    ]
